Change parentnet
XinFinOrg/XDC-Subnet pull request #72
Opened 2023-08-07 14:56 UTC by wanwiset25

2023-08-07 15:02 UTC, GalaxySciTech requested changes

2023-08-07 15:02 UTC, GalaxySciTech commented on mainnet_contract/hardhat.config.js
> +      url: deploy["xdcparentnet"],
depoly file variable `xdcparentnet` need change too

2023-08-07 15:03 UTC, GalaxySciTech commented on mainnet_contract/hardhat.config.js
> +      url: deploy["xdcparentnet"],
https://github.com/XinFinOrg/XDC-Subnet/blob/5910df87930d597ef306ffcc09487765ca1903d2/mainnet_contract/deployment.json#L9

2023-08-07 15:08 UTC, GalaxySciTech approved these changes

2023-08-08 12:49 UTC, liam-lai approved these changes
Good naming!

2023-08-09 08:53 UTC, merged