add new validator contract
XinFinOrg/XDC-Subnet pull request #77
Opened 2023-08-16 13:38 UTC by GalaxySciTech

add new validator contract

2023-08-16 14:32 UTC, wgr523 requested changes
so many js/json/... files and I think we should remove them. we only need sol file for reading code. and we need validator.go to deploy.

2023-08-16 15:16 UTC, GalaxySciTech commented
> 
I kept it clean and put the code in a new folder
https://github.com/XinFinOrg/XDC-Subnet/pull/77/commits/1997a2f53fae14acf5f1f21f67367d60bdac66ee

2023-08-16 15:16 UTC, GalaxySciTech commented
> so many js/json/... files and I think we should remove them. we only need sol file for reading code. and we need validator.go to deploy.
I kept it clean and put the code in a new folder
https://github.com/XinFinOrg/XDC-Subnet/pull/77/commits/1997a2f53fae14acf5f1f21f67367d60bdac66ee

2023-08-17 15:10 UTC, wgr523 commented on contracts/validator/core/abigen
I think we can remove this large file

2023-08-17 15:13 UTC, GalaxySciTech commented on contracts/validator/core/abigen
> I think we can remove this large file

it is convince to gen validator.go

if remove, some need install go path and compile the abigen code it will complexity

2023-08-17 15:22 UTC, wgr523 commented on contracts/validator/core/README.md
> +2, run
2. not 2,

2023-08-17 15:23 UTC, wgr523 commented on contracts/validator/core/README.md
> +1.run generate script to genera
space between 1.run. should write `1. run`

2023-08-17 15:23 UTC, wgr523 commented on contracts/validator/core/README.md
> +3.Go `../contract/validator.go` change `github.com/ethereum/go-ethereum` to `ethereum "github.com/XinFinOrg/XDC-Subnet"`
`3. Go`

2023-08-17 15:30 UTC, GalaxySciTech commented on contracts/validator/core/README.md
> +3.Go `../contract/validator.go` change `github.com/ethereum/go-ethereum` to `ethereum "github.com/XinFinOrg/XDC-Subnet"`
fixed

2023-08-19 13:14 UTC, wgr523 commented on contracts/validator/core/abigen
I think it is too big for github.
Also, users don't need abigen. Only we use abigen

2023-08-20 03:49 UTC, GalaxySciTech commented on contracts/validator/core/abigen
removed

2023-08-20 04:16 UTC, wgr523 commented
you put solidity source code in a folder "core". Is "core" the name used in hardhat? I think "src" is better

2023-08-20 04:29 UTC, GalaxySciTech commented
> you put solidity source code in a folder "core". Is "core" the name used in hardhat? I think "src" is better

fixed

2023-08-20 05:33 UTC, wgr523 approved these changes

2023-08-20 05:41 UTC, merged